version: 2
updates:

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/terraform" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      terraform:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      github-actions:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    versioning-strategy: increase
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      composer-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Pin Drupal core to 10.x
      - dependency-name: "drupal/core-*"
        update-types: ["version-update:semver-major"]
      # Pin Bootstrap theme to 3.x
      - dependency-name: "drupal/bootstrap"
        update-types: ["version-update:semver-major"]
